import { AdminRole } from '@prisma/client';

export enum AdminPermission {
  SETTLEMENT_VIEW = 'settlement.view',
  SETTLEMENT_REVIEW = 'settlement.review',
  SETTLEMENT_OVERRIDE = 'settlement.override',
  SETTLEMENT_RETRY = 'settlement.retry',
  MERCHANT_CREATE = 'merchant.create',
  MERCHANT_VIEW = 'merchant.view',
  MERCHANT_SUSPEND = 'merchant.suspend',
  USER_VIEW = 'user.view',
  USER_EDIT = 'user.edit',
  USER_FREEZE = 'user.freeze',
  USER_BAN = 'user.ban',
  USER_UNBAN = 'user.unban',
  ADMIN_NOTES_READ = 'admin_notes.read',
  ADMIN_NOTES_WRITE = 'admin_notes.write',
  USER_TIMELINE_VIEW = 'user_timeline.view',
  RISK_MANAGE = 'risk.manage',
  FINANCIAL_VIEW = 'financial.view',
  LEDGER_VIEW = 'ledger.view',
  BALANCE_ADJUST = 'balance.adjust',
  WITHDRAWAL_APPROVE = 'withdrawal.approve',
  WITHDRAWAL_REJECT = 'withdrawal.reject',
  DEPOSIT_VERIFY = 'deposit.verify',
  TREASURY_VIEW = 'treasury.view',
  FINANCIAL_EXPORT = 'financial.export',
  SUPPORT_MANAGE = 'support.manage',
  METRICS_VIEW = 'metrics.view',
  TREASURY_MANAGE = 'treasury.manage',
  GAME_MANAGE = 'game.manage',
  MACHINE_VIEW = 'machine.view',
  MACHINE_EDIT = 'machine.edit',
  MACHINE_CREATE = 'machine.create',
  MACHINE_DELETE = 'machine.delete',
  OUTPUT_EDIT = 'output.edit',
  LICENSE_VIEW = 'license.view',
  LICENSE_GRANT = 'license.grant',
  LICENSE_REVOKE = 'license.revoke',
  LICENSE_SUSPEND = 'license.suspend',
  ECONOMY_VIEW = 'economy.view',
  ECONOMY_EDIT = 'economy.edit',
  PROMOTION_CREATE = 'promotion.create',
  PROMOTION_APPROVE = 'promotion.approve',
  MAINTENANCE_CONTROL = 'maintenance.control',
  SIMULATION_RUN = 'simulation.run',
}

export const ROLE_PERMISSIONS_MAP: Record<AdminRole, AdminPermission[]> = {
  [AdminRole.SUPER_ADMIN]: Object.values(AdminPermission),
  [AdminRole.OPERATIONS_ADMIN]: [
    AdminPermission.SETTLEMENT_VIEW,
    AdminPermission.SETTLEMENT_REVIEW,
    AdminPermission.SETTLEMENT_OVERRIDE,
    AdminPermission.SETTLEMENT_RETRY,
    AdminPermission.MERCHANT_CREATE,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.MERCHANT_SUSPEND,
    AdminPermission.USER_VIEW,
    AdminPermission.USER_EDIT,
    AdminPermission.USER_FREEZE,
    AdminPermission.USER_BAN,
    AdminPermission.USER_UNBAN,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.FINANCIAL_VIEW,
    AdminPermission.LEDGER_VIEW,
    AdminPermission.WITHDRAWAL_APPROVE,
    AdminPermission.WITHDRAWAL_REJECT,
    AdminPermission.DEPOSIT_VERIFY,
    AdminPermission.SUPPORT_MANAGE,
    AdminPermission.GAME_MANAGE,
    AdminPermission.MACHINE_VIEW,
    AdminPermission.MACHINE_EDIT,
    AdminPermission.MACHINE_CREATE,
    AdminPermission.MACHINE_DELETE,
    AdminPermission.OUTPUT_EDIT,
    AdminPermission.LICENSE_VIEW,
    AdminPermission.LICENSE_GRANT,
    AdminPermission.LICENSE_REVOKE,
    AdminPermission.LICENSE_SUSPEND,
    AdminPermission.ECONOMY_VIEW,
    AdminPermission.ECONOMY_EDIT,
    AdminPermission.PROMOTION_CREATE,
    AdminPermission.PROMOTION_APPROVE,
    AdminPermission.MAINTENANCE_CONTROL,
    AdminPermission.SIMULATION_RUN,
  ],
  [AdminRole.FINANCE_ADMIN]: [
    AdminPermission.FINANCIAL_VIEW,
    AdminPermission.LEDGER_VIEW,
    AdminPermission.BALANCE_ADJUST,
    AdminPermission.WITHDRAWAL_APPROVE,
    AdminPermission.WITHDRAWAL_REJECT,
    AdminPermission.DEPOSIT_VERIFY,
    AdminPermission.SETTLEMENT_VIEW,
    AdminPermission.SETTLEMENT_REVIEW,
    AdminPermission.SETTLEMENT_RETRY,
    AdminPermission.TREASURY_VIEW,
    AdminPermission.TREASURY_MANAGE,
    AdminPermission.FINANCIAL_EXPORT,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.USER_VIEW,
  ],
  [AdminRole.RISK_OPERATOR]: [
    AdminPermission.RISK_MANAGE,
    AdminPermission.USER_VIEW,
    AdminPermission.USER_FREEZE,
    AdminPermission.USER_BAN,
    AdminPermission.USER_UNBAN,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.FINANCIAL_VIEW,
    AdminPermission.LEDGER_VIEW,
    AdminPermission.SETTLEMENT_VIEW,
    AdminPermission.WITHDRAWAL_REJECT,
  ],
  [AdminRole.MERCHANT_MANAGER]: [
    AdminPermission.MERCHANT_CREATE,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.MERCHANT_SUSPEND,
  ],
  [AdminRole.SUPPORT_AGENT]: [
    AdminPermission.USER_VIEW,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.FINANCIAL_VIEW,
    AdminPermission.SUPPORT_MANAGE,
    AdminPermission.SETTLEMENT_VIEW,
  ],
};
