import { AdminRole } from '@prisma/client';

export enum AdminPermission {
  SETTLEMENT_VIEW = 'settlement.view',
  SETTLEMENT_REVIEW = 'settlement.review',
  SETTLEMENT_OVERRIDE = 'settlement.override',
  MERCHANT_CREATE = 'merchant.create',
  MERCHANT_VIEW = 'merchant.view',
  MERCHANT_SUSPEND = 'merchant.suspend',
  USER_VIEW = 'user.view',
  USER_EDIT = 'user.edit',
  USER_FREEZE = 'user.freeze',
  USER_BAN = 'user.ban',
  USER_UNBAN = 'user.unban',
  ADMIN_NOTES_READ = 'admin_notes.read',
  ADMIN_NOTES_WRITE = 'admin_notes.write',
  USER_TIMELINE_VIEW = 'user_timeline.view',
  RISK_MANAGE = 'risk.manage',
  FINANCIAL_VIEW = 'financial.view',
  SUPPORT_MANAGE = 'support.manage',
  METRICS_VIEW = 'metrics.view',
  TREASURY_MANAGE = 'treasury.manage',
  GAME_MANAGE = 'game.manage',
}

export const ROLE_PERMISSIONS_MAP: Record<AdminRole, AdminPermission[]> = {
  [AdminRole.SUPER_ADMIN]: Object.values(AdminPermission),
  [AdminRole.OPERATIONS_ADMIN]: [
    AdminPermission.SETTLEMENT_VIEW,
    AdminPermission.SETTLEMENT_REVIEW,
    AdminPermission.SETTLEMENT_OVERRIDE,
    AdminPermission.MERCHANT_CREATE,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.MERCHANT_SUSPEND,
    AdminPermission.USER_VIEW,
    AdminPermission.USER_EDIT,
    AdminPermission.USER_FREEZE,
    AdminPermission.USER_BAN,
    AdminPermission.USER_UNBAN,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.SUPPORT_MANAGE,
    AdminPermission.GAME_MANAGE,
  ],
  [AdminRole.FINANCE_ADMIN]: [
    AdminPermission.FINANCIAL_VIEW,
    AdminPermission.SETTLEMENT_VIEW,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.USER_VIEW,
  ],
  [AdminRole.RISK_OPERATOR]: [
    AdminPermission.RISK_MANAGE,
    AdminPermission.USER_VIEW,
    AdminPermission.USER_FREEZE,
    AdminPermission.USER_BAN,
    AdminPermission.USER_UNBAN,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.SETTLEMENT_VIEW,
  ],
  [AdminRole.MERCHANT_MANAGER]: [
    AdminPermission.MERCHANT_CREATE,
    AdminPermission.MERCHANT_VIEW,
    AdminPermission.MERCHANT_SUSPEND,
  ],
  [AdminRole.SUPPORT_AGENT]: [
    AdminPermission.USER_VIEW,
    AdminPermission.ADMIN_NOTES_READ,
    AdminPermission.ADMIN_NOTES_WRITE,
    AdminPermission.USER_TIMELINE_VIEW,
    AdminPermission.SUPPORT_MANAGE,
    AdminPermission.SETTLEMENT_VIEW,
  ],
};
